[tools]
python = "latest"
pipx = "latest"
bat = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
helm = "latest"
kubectl = "latest"
nsc = "latest"
node = "latest"
npm = "latest"
bun = "latest"
rust = "latest"
starship = "latest"
opentofu = "latest"

"go:github.com/erikkinding/sk" = "latest"
"go:github.com/nats-io/nats-server/v2" = "latest"
"go:github.com/nats-io/natscli/nats" = "latest"
"go:github.com/steveyegge/beads/cmd/bd" = "latest"
"go:github.com/Dicklesworthstone/beads_viewer/cmd/bv" = "latest"

"ubi:jesseduffield/lazygit" = "latest"
"ubi:gokcehan/lf" = "latest"
"ubi:kovidgoyal/kitty" = "latest"
"ubi:GoogleContainerTools/skaffold" = "latest"
"ubi:mrjosh/helm-ls" = "latest"

"npm:yarn" = "latest"
"npm:yaml-language-server" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@github/copilot" = "latest"
"npm:opencode-ai" = "latest"
"npm:oh-my-opencode" = "latest"

ansible = "latest"
velero = "latest"
crossplane = "latest"
kubeconform = "latest"
kuttl = "latest"

[settings]
experimental = true

[settings.python]
compile = false
